version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: school_management
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://user:password@localhost:5432/school?schema=public
    depends_on:
      - postgres
