import { DefaultClass } from 'src/class/enum/class';

export const SubjectsForClasses = {
  [DefaultClass.PRIMARY_1]: [
    'Mathematics',
    'English',
    'Science',
    'Social Studies',
  ],
  [DefaultClass.PRIMARY_2]: [
    'Mathematics',
    'English',
    'Science',
    'Social Studies',
  ],
  [DefaultClass.PRIMARY_3]: [
    'Mathematics',
    'English',
    'Science',
    'Social Studies',
    'Arts',
  ],
  [DefaultClass.PRIMARY_4]: [
    'Mathematics',
    'English',
    'Science',
    'Social Studies',
    'Arts',
  ],
  [DefaultClass.PRIMARY_5]: [
    'Mathematics',
    'English',
    'Science',
    'Social Studies',
    'ICT',
  ],
  [DefaultClass.PRIMARY_6]: [
    'Mathematics',
    'English',
    'Science',
    'Social Studies',
    'ICT',
  ],
  [DefaultClass.JSS_1]: [
    'Mathematics',
    'English',
    'Basic Science',
    'Basic Technology',
    'Civic Education',
  ],
  [DefaultClass.JSS_2]: [
    'Mathematics',
    'English',
    'Basic Science',
    'Basic Technology',
    'Civic Education',
    'History',
  ],
  [DefaultClass.JSS_3]: [
    'Mathematics',
    'English',
    'Basic Science',
    'Basic Technology',
    'Civic Education',
    'History',
  ],
  [DefaultClass.SS_1]: [
    'Mathematics',
    'English',
    'Physics',
    'Chemistry',
    'Biology',
    'Literature',
  ],
  [DefaultClass.SS_2]: [
    'Mathematics',
    'English',
    'Physics',
    'Chemistry',
    'Biology',
    'Literature',
    'Economics',
  ],
  [DefaultClass.SS_3]: [
    'Mathematics',
    'English',
    'Physics',
    'Chemistry',
    'Biology',
    'Literature',
    'Economics',
  ],
};
